# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rematter < Formula
  desc "Markdown frontmatter transformations cli"
  homepage "https://github.com/g15r/rematter"
  url "https://github.com/g15r/rematter/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "45e6bf8b578eecc422d3dfcff5ca522a1bb7663a33ec89e05a064a91962b923d"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/g15r/rematter/releases/download/v0.1.0/rematter-0.1.0-darwin-amd64.tar.gz"
      sha256 "41aec569a534ea3cdbcd0c8fa216a25e30aa931f0b1d12e03e25c5da05efbcb1"
    end

    on_arm do
      url "https://github.com/g15r/rematter/releases/download/v0.1.0/rematter-0.1.0-darwin-arm64.tar.gz"
      sha256 "897984bce45a95016e898418a016f34ebdb6eaac6885404bc83ad2716e0e6a06"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/g15r/rematter/releases/download/v0.1.0/rematter-0.1.0-linux-amd64.tar.gz"
      sha256 "3b403dbd4cf8f5c107011cb529bafb43ad45829ca27123c9ceed7df077af8785"
    end

    on_arm do
      url "https://github.com/g15r/rematter/releases/download/v0.1.0/rematter-0.1.0-linux-arm64.tar.gz"
      sha256 "53d63476012612ce15d20972769fe04a5488c6aaa9e65cb2b8d9092661e35b29"
    end
  end

  def install
    bin.install "rematter"
  end

  test do
    assert_match("Usage", shell_output("#{bin}/rematter --help"))
  end
end
