# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Winline < Formula
  desc "Pretty and performant claude code statusline"
  homepage "https://github.com/supermodellabs/winline"
  url "https://github.com/supermodellabs/winline/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "b06f7d803aa16f02464dfd44e491920c6f9ed052c7d5c1336a5a61a827a23923"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.1/winline-0.2.1-darwin-amd64.tar.gz"
      sha256 "1f829880fae88dc32c42a2bc1046a92bcaa5ea93ef9085d8873e9a099703925d"
    end

    on_arm do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.1/winline-0.2.1-darwin-arm64.tar.gz"
      sha256 "713388d0bc94ad055b608173ed35a62ac56c807c78932c80c6bbaaf3e7c8e876"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.1/winline-0.2.1-linux-amd64.tar.gz"
      sha256 "418497b35f1cc29280091b923c6ea8049ae9c30277f5007be4487eea7e0ef9ad"
    end

    on_arm do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.1/winline-0.2.1-linux-arm64.tar.gz"
      sha256 "b6f9ea2ca50289c1eb1cf4b5c27de2dcee7fe34323dee08f755ee0125c035b55"
    end
  end

  def install
    bin.install "winline"
  end

  test do
    assert_match("winline", shell_output("#{bin}/winline --help"))
  end
end
