# typed: false
# frozen_string_literal: true

# This file gets re-generated by homebrew-releaser. Do not edit manually.
class Winline < Formula
  desc "Polished and performant Claude Code statusline with easy configurability and great extras"
  homepage "https://github.com/gwenwindflower/winline"
  version "0.1.0"
  license "MIT"
  on_macos do
    on_arm do
      url "https://github.com/gwenwindflower/winline/releases/download/v#{version}/winline-#{version}-darwin-arm64.tar.gz"
      sha256 "PLACEHOLDER_DARWIN_ARM64_SHA256"
    end
    on_intel do
      url "https://github.com/gwenwindflower/winline/releases/download/v#{version}/winline-#{version}-darwin-amd64.tar.gz"
      sha256 "PLACEHOLDER_DARWIN_AMD64_SHA256"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/gwenwindflower/winline/releases/download/v#{version}/winline-#{version}-linux-arm64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_ARM64_SHA256"
    end
    on_intel do
      url "https://github.com/gwenwindflower/winline/releases/download/v#{version}/winline-#{version}-linux-amd64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_AMD64_SHA256"
    end
  end
  def install
    bin.install "winline"
  end
  test do
    assert_match "USAGE", shell_output("#{bin}/winline --help 2>&1", 1)
  end
end
