# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Winline < Formula
  desc "Pretty and performant claude code statusline"
  homepage "https://github.com/supermodellabs/winline"
  url "https://github.com/supermodellabs/winline/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "68edf751f1dcd36ef11d767a555f932332b9a53eff0deb98ddf8bceb8c48ac6f"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.0/winline-0.2.0-darwin-amd64.tar.gz"
      sha256 "8533b5d5e534d3f45cfede84790326d9052e16fa7d34a23d2cb920c284956b59"
    end

    on_arm do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.0/winline-0.2.0-darwin-arm64.tar.gz"
      sha256 "77a097aa94ffa68d9a72feb8212cea82c63b25e80fd2f3957d57aedaf3c4805e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.0/winline-0.2.0-linux-amd64.tar.gz"
      sha256 "f91f1905d699b227e88ec6d31dfb680316387ad752fa7bdc0790fa1fa51e955d"
    end

    on_arm do
      url "https://github.com/supermodellabs/winline/releases/download/v0.2.0/winline-0.2.0-linux-arm64.tar.gz"
      sha256 "98d7dccce5bd29c91a8ffd52fb11d998a2df2a483f4b6e2a9ea449717c0b5b7e"
    end
  end

  def install
    bin.install "winline"
  end

  test do
    assert_match("winline", shell_output("#{bin}/winline --help"))
  end
end
